### ISSUE TITLE
Could you please let me know how to deploy the examples in detail?

### ISSUE THREAD

**Issue by puremjlee** [signalfx/splunk-otel-java-lambda#33]
@kubawach 

Hi, I built your examples with gradle, then upload the .zip file to the lambda function code on AWS console. It throws the error 'class not found'. Could you please let me know how to deploy the examples in detail?
```
Error loading class com.splunk.support.lambda.examples.TracingRequestWrapper: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: java.lang.RuntimeException: com.splunk.support.lambda.examples.RequestFunction not found in classpath
	at io.opentelemetry.instrumentation.awslambda.v1_0.WrappedLambda.fromConfiguration(WrappedLambda.java:51)
	at io.opentelemetry.instrumentation.awslambda.v1_0.TracingRequestWrapperBase.<clinit>(TracingRequestWrapperBase.java:30)
	... 2 more
```

**Comment by kubawach** [comment]
Hi @puremjlee thanks for your report. General advice is to deploy the examples using SAM as described in README.MD files (eg https://github.com/signalfx/splunk-otel-java-lambda/tree/main/examples/splunk-wrapper)

I haven't tried uploading the ZIP manually, but I guess it should just work. If you still prefer the manual way, please describe the scenario completely (which example bundle, gradle command, AWS console steps).

**Comment by kubawach** [comment]
@puremjlee has above ^^ fixed your problem? Let us know, otherwise I'll assume it did and close this issue.

**Comment by drissamri** [comment]
I have tried to implement this for my own functions but got the same error. 

To see if this was my implementation or the wrapper not working, I have cloned this repo and tried to build everything but this fails already due to dependencie retrieved from Bintray which gives a 403 (bintray is not public anymore)
```
On February 3 2021, JFrog announced that they will be shutting down Bintray and JCenter. This post tells you what you need to know and do to avoid disruptions to your build pipelines.2
```

This is only applicable for the `splunk-wrapper` so I have deleted this one and tried to deploy the `splunk-layer` but this fails with the same error as @puremjlee 
```
Error loading class com.splunk.support.lambda.examples.TracingRequestWrapper: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
```

**Comment by Thul95** [comment]
Also commenting to give this some traction. Done pretty much te same as Drissamri, first thing you bounce on are the Bintray dependencies in the `splunk-wrapper`.

**Comment by kubawach** [comment]
FYI - PR removing offending repos has just been opened. Anyways, I recommend deploying examples using `sam build && sam deploy`. Let me know about the results.

**Comment by drissamri** [comment]
Can you remove your .m2 folder and try again? 
```
* What went wrong:
Execution failed for task ':splunk-wrapper:compileJava'.
> Could not resolve all files for configuration ':splunk-wrapper:compileClasspath'.
   > Could not find com.signalfx.public:otel-java-lambda-wrapper:0.0.12-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/drissamri/.m2/repository/com/signalfx/public/otel-java-lambda-wrapper/0.0.12-SNAPSHOT/maven-metadata.xml
       - file:/Users/drissamri/.m2/repository/com/signalfx/public/otel-java-lambda-wrapper/0.0.12-SNAPSHOT/otel-java-lambda-wrapper-0.0.12-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/signalfx/public/otel-java-lambda-wrapper/0.0.12-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/signalfx/public/otel-java-lambda-wrapper/0.0.12-SNAPSHOT/otel-java-lambda-wrapper-0.0.12-SNAPSHOT.pom
     Required by:
         project :splunk-wrapper
```

**Comment by kubawach** [comment]
@drissamri how's your testing? Managed to run the examples?

**Comment by kubawach** [comment]
Out of side conversation - seems that the examples run successfully, so closing the ticket.
